# Generated by Django 4.2.25 on 2026-02-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ingredient_dish_instructions_dishingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dish',
            name='carbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dish',
            name='fat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dish',
            name='protein',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dishingredient',
            name='weight_g',
            field=models.FloatField(default=0),
        ),
    ]
