# Generated by Django 4.2.25 on 2026-05-28 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fridgeitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncompatibleIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('ingredient_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incompatibilities_1', to='core.ingredient')),
                ('ingredient_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incompatibilities_2', to='core.ingredient')),
            ],
            options={
                'verbose_name': 'Несумісність інгредієнтів',
                'verbose_name_plural': 'Несумісності інгредієнтів',
                'unique_together': {('ingredient_1', 'ingredient_2')},
            },
        ),
    ]
