# Generated by Django 4.2.25 on 2026-05-28 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_incompatibleingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Збережений план',
                'verbose_name_plural': 'Збережені плани',
                'ordering': ['-created_at'],
            },
        ),
    ]
