# Generated by Django 4.2.25 on 2026-05-28 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_savedplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedplan',
            options={'verbose_name': 'Збережений план', 'verbose_name_plural': 'Збережені плани'},
        ),
        migrations.AlterField(
            model_name='savedplan',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='savedplan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved_plan', to=settings.AUTH_USER_MODEL),
        ),
    ]
